- name: Basic
  tags:
    - basic
  block:
    - name: Install basic system tools
      block:
        - name: Install basic system tools (Ubuntu)
          ansible.builtin.apt:
            name:
              - zsh
              - curl
              - git
              - build-essential
              - tmux
              - openssh-client
              - unzip
              - file
              - htop
              - silversearcher-ag
              - w3m
              - npm
            state: present
            update_cache: true
          become: true
          become_user: root
          when: ansible_facts['distribution'] == "Ubuntu"

        - name: Install basic system tools (AL2)
          ansible.builtin.shell: |
            sudo yum install -y \
                "@Development tools" \
                cmake curl tmux htop findutils \
                gcc make patch zlib-devel bzip2 bzip2-devel \
                readline-devel sqlite sqlite-devel openssl11-devel \
                tk-devel libffi-devel xz xz-devel libevent-devel
            touch ~/.installed_basic_system_tools_al2
          args:
            creates: ~/.installed_basic_system_tools_al2
          when: ansible_facts["distribution"] == "Amazon"

    - name: Install fzf
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        depth: 1
        version: 0.24.3
    - name: Setup fzf for users shell
      ansible.builtin.command: ~/.fzf/install --all
      args:
        creates: ~/.fzf/bin/fzf

    # x86_64 static binaries to install
    - name: "{{ item.name }}"
      ansible.builtin.include_tasks: static_binary_install.yml
      when: ansible_facts["architecture"] == "x86_64"
      with_items:
        - { name: "Ripgrep",
            src: "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz",
            archive_path: "ripgrep-13.0.0-x86_64-unknown-linux-musl/rg",
            bin_name: "rg" }
        - { name: "Starship",
            src: "https://github.com/starship/starship/releases/download/v1.13.0/starship-x86_64-unknown-linux-musl.tar.gz",
            archive_path: "starship",
            bin_name: "starship" }
        - { name: "Bat",
            src: "https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-i686-unknown-linux-musl.tar.gz",
            archive_path: "bat-v0.22.1-i686-unknown-linux-musl/bat",
            bin_name: "bat" }
        - { name: "Eza",
            src: "https://github.com/eza-community/eza/releases/download/v0.20.7/eza_x86_64-unknown-linux-musl.tar.gz",
            archive_path: "eza",
            bin_name: "eza" }

    # aarch64 static binaries to install
    - name: "{{ item.name }}"
      ansible.builtin.include_tasks: static_binary_install.yml
      when: ansible_facts["architecture"] == "aarch64"
      with_items:
        - { name: "Ripgrep",
            src: "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-aarch64-unknown-linux-gnu.tar.gz",
            archive_path: "ripgrep-14.1.0-aarch64-unknown-linux-gnu/rg",
            bin_name: "rg" }
        - { name: "Starship",
            src: "https://github.com/starship/starship/releases/download/v1.18.2/starship-aarch64-unknown-linux-musl.tar.gz",
            archive_path: "starship",
            bin_name: "starship" }
        - { name: "Bat",
            src: "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-aarch64-unknown-linux-gnu.tar.gz",
            archive_path: "bat-v0.24.0-aarch64-unknown-linux-gnu/bat",
            bin_name: "bat" }
        - { name: "Exa",
            src: "https://github.com/eza-community/eza/releases/download/v0.20.7/eza_aarch64-unknown-linux-gnu.tar.gz",
            archive_path: "eza",
            bin_name: "eza" }
