- name: Install dotfiles repo
  block:
    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/benjaminfjones/dotfiles
        dest: ~/dotfiles
        version: stable-20230225

    - name: Boot dotfiles
      ansible.builtin.command:
        cmd: bash boot.sh
        chdir: ~/dotfiles
      args:
        # TODO: have boot.sh create a flag file to check here
        creates: ~/.config/nvim/init.lua

    - name: Copy gitconfig
      ansible.builtin.copy:
        src: gitconfig
        dest: ~/.gitconfig
        owner: ubuntu
        group: ubuntu
        mode: u=rw,g=r,o=r

    - name: Copy zshrc_local
      ansible.builtin.copy:
        src: zshrc_local
        dest: ~/.zshrc_local
        owner: ubuntu
        group: ubuntu
        mode: u=rw,g=r,o=r

    - name: Ensure zsh installed in /usr/bin
      ansible.builtin.stat:
        path: /usr/bin/zsh
      register: zsh_path

    - name: Set users shell to zsh
      ansible.builtin.user:
        name: ubuntu
        shell: /usr/bin/zsh
      become: true
      become_user: root
      when: zsh_path.stat.exists
