- name: Install dotfiles repo
  tags:
    - dotfiles
  block:
    - name: Clone dotfiles repo
      ansible.builtin.git:
        repo: https://github.com/benjaminfjones/dotfiles
        dest: ~/dotfiles
        version: stable-20230225
      register: dotfiles_clone
      failed_when:
        - dotfiles_clone.failed
        - not 'Local modifications exist in the destination' in dotfiles_clone.msg

    - name: Boot dotfiles
      ansible.builtin.command:
        cmd: bash boot.sh
        chdir: ~/dotfiles
      args:
        creates: ~/.tmux.conf

    - name: Copy gitconfig
      ansible.builtin.copy:
        src: gitconfig
        dest: ~/.gitconfig
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: u=rw,g=r,o=r

    - name: Copy zshrc_local
      ansible.builtin.copy:
        src: zshrc_local
        dest: ~/.zshrc_local
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: u=rw,g=r,o=r

    - name: Ensure zsh installed in /usr/bin
      ansible.builtin.stat:
        path: /usr/bin/zsh
      register: zsh_path

    - name: Set users shell to zsh
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh
      become: true
      become_user: root
      when: zsh_path.stat.exists and ansible_facts['distribution'] == "Ubuntu"
