- name: Neovim
  tags:
    - neovim
  block:
  - name: Install neovim system dependencies
    ansible.builtin.apt:
      name:
        - ninja-build
        - gettext
        - libtool
        - libtool-bin
        - cmake
        - g++
        - pkg-config
        - unzip
        - curl
        - doxygen
        - software-properties-common
        - python3-dev
        - python3-setuptools
        - python3-neovim
      state: present
    become: true
    become_user: root

  - name: Install Neovim from source
    block:
      - name: Ensure src directory exists
        ansible.builtin.file:
          path: ~/src
          state: directory
          mode: u=rwx,g=rx,o=rx
        register: src_dir
      - name: Fetch neovim source
        ansible.builtin.git:
          repo: https://github.com/neovim/neovim
          dest: "{{ src_dir.path }}/neovim"
          version: stable
          depth: 1  # make a shallow clone
        register: neovim_repo
      - name: Build neovim
        ansible.builtin.command: make CMAKE_BUILD_TYPE=RelWithDebInfo
        args:
          chdir: "{{ src_dir.path }}/neovim"
          creates: "{{ src_dir.path }}/neovim/build"
      - name: Install neovim
        become: true
        become_user: root
        ansible.builtin.command: make install
        args:
          chdir: "{{ src_dir.path }}/neovim"
          creates: /usr/local/bin/nvim

  - name: Clone neovim config repository
    ansible.builtin.git:
      repo: https://github.com/benjaminfjones/kickstart.nvim.git
      dest: ~/.config/nvim
      version: v0.1.0

  - name: Boot neomvim configuration
    ansible.builtin.command: /usr/local/bin/nvim +qa
