---
# This ansible playbook contains plays to setup a development environment

- name: Provision AL2 hosts
  hosts: cloud_dev_al2
  tasks:
    - name: Basic
      ansible.builtin.include_tasks: basic.yml
      tags:
        - basic
    - name: Python
      ansible.builtin.include_tasks: python.yml
      tags:
        - python
    # TODO: also need npm
    - name: Node
      ansible.builtin.include_tasks: node.yml
      tags:
        - node
    - name: Dotfiles
      ansible.builtin.include_tasks: dotfiles.yml
      tags:
        - dotfiles
    - name: Neovim
      ansible.builtin.include_tasks: neovim.yml
      tags:
        - neovim
