---
# This ansible playbook contains plays to setup a development environment

- hosts: all
  tasks:
  - include_tasks: basic.yml
  - include_tasks: nix-home-manager.yml
  - include_tasks: sourcecode.yml
