---
# This ansible playbook contains plays to setup a development environment

- name: Provision ubuntu hosts
  hosts: all
  tasks:
    - name: Basic
      ansible.builtin.include_tasks: basic.yml
      tags:
        - basic
    - name: Python
      ansible.builtin.include_tasks: python.yml
    - include_tasks: node.yml
      tags:
        - node
    - name: Neovim
      ansible.builtin.include_tasks: neovim.yml
      tags:
        - neovim
    - name: fish
      ansible.builtin.include_tasks: fish.yml
      tags:
        - fish
    - name: Dotfiles
      ansible.builtin.include_tasks: dotfiles.yml
    - name: Rust
      ansible.builtin.include_tasks: rust.yml
      tags:
        - rust
    - name: Source code
      ansible.builtin.include_tasks: sourcecode.yml
