- name: Rust
  tags:
    - rust
  block:
  - name: Fetch rustup installer
    ansible.builtin.get_url:
      url: https://sh.rustup.rs
      dest: /tmp/install_rustup.sh
      mode: u=rwx,g=rx,o=rx

  - name: Install rustup
    ansible.builtin.command: /bin/bash /tmp/install_rustup.sh -y
    args:
      creates: ~/.cargo/bin/rustup

  - name: Install rust components
    ansible.builtin.command: >
        ~/.cargo/bin/rustup component add \
            cargo \
            clippy \
            miri \
            rls \
            rust \
            rust-docs \
            rust-src \
            rust-analysis \
            rust-analyzer-preview \
            rustc \
            rustfmt
    args:
      creates: ~/.cargo/bin/cargo-clippy

  # Install shell goodies
  - name: Ensure .zfunc dir exists
    ansible.builtin.file:
      path: ~/.zfunc
      state: directory
      mode: u=rwx,g=rx,o=rx
  - name: Install rustup completions
    ansible.builtin.shell: ~/.cargo/bin/rustup completions zsh > ~/.zfunc/_rustup
    args:
      creates: ~/.zfunc/_rustup
