---
# Clone all currently active repos

- name: Create src directory
  ansible.builtin.file:
    path: ~/src
    state: directory
    mode: 0755

- name: Copy get_repo script
  ansible.builtin.copy:
    src: get_repos.sh
    dest: ~/src/get_repos.sh
    mode: 0755

- name: Copy clone_repo script
  ansible.builtin.copy:
    src: clone_repos.sh
    dest: ~/src/clone_repos.sh
    mode: 0755

- name: Copy repositories index
  ansible.builtin.copy:
    src: repositories.txt
    dest: ~/src/repositories.txt
    mode: 0644
