# Clone all currently active repos

- name: Create src directory
  ansible.builtin.file:
    path: ~/src
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy get_repo script
  ansible.builtin.copy:
    src: get_repos.sh
    dest: ~/src/get_repos.sh
    mode: u=rwx,g=rx,o=rx
- name: Copy clone_repo script
  ansible.builtin.copy:
    src: clone_repos.sh
    dest: ~/src/clone_repos.sh
    mode: u=rwx,g=rx,o=rx
- name: Copy repositories index
  ansible.builtin.copy:
    src: repositories.txt
    dest: ~/src/repositories.txt
    mode: u=rw,g=r,o=r

# TODO: setup ssh keys manually
# Github credentials
# - name: Create .ssh directory
#   file:
#     path: ~/.ssh
#     state: directory
#     mode: 0755
# - name: Copy github ssh private key
#   copy:
#     src: id_rsa
#     dest: ~/.ssh/id_rsa
#     mode: 0600
# - name: Copy github ssh public key
#   copy:
#     src: id_rsa.pub
#     dest: ~/.ssh/id_rsa.pub
#     mode: 0644
